-- MySQL Script generated by MySQL Workbench
-- 06/21/17 15:59:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fb` DEFAULT CHARACTER SET utf8 ;
USE `fb` ;

-- -----------------------------------------------------
-- Table `fb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`profile` (
  `userid` VARCHAR(32) NOT NULL,
  `firstname` TEXT NOT NULL,
  `lastname` TEXT NOT NULL,
  `mail` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `dob` DATE NOT NULL,
  `gender` TEXT NOT NULL,
  `highschool` TEXT NULL DEFAULT NULL,
  `college` TEXT NULL DEFAULT NULL,
  `work` TEXT NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `quote` TEXT NULL DEFAULT NULL,
  `interest` TEXT NULL DEFAULT NULL,
  `religious` TEXT NULL DEFAULT NULL,
  `phone` TEXT NULL DEFAULT NULL,
  `currentcity` TEXT NULL DEFAULT NULL,
  `hometown` TEXT NULL DEFAULT NULL,
  `relationstatus` TEXT NULL DEFAULT NULL,
  `profilepic` TEXT NOT NULL,
  `role` TEXT NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`product` (
  `productid` VARCHAR(60) NOT NULL,
  `uploaderid` VARCHAR(32) NOT NULL,
  `textdata` TEXT NULL DEFAULT NULL,
  `images` TEXT NULL DEFAULT NULL,
  `videos` TEXT NULL DEFAULT NULL,
  `shares` INT(11) NOT NULL,
  `likes` INT(11) NOT NULL,
  `comments` INT(11) NOT NULL,
  PRIMARY KEY (`productid`),
  INDEX `myindex_idx` (`uploaderid` ASC),
  CONSTRAINT `myindex`
    FOREIGN KEY (`uploaderid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`activity` (
  `activityid` VARCHAR(60) NOT NULL,
  `userid` VARCHAR(32) NOT NULL,
  `activitytype` TEXT NOT NULL,
  `productid` VARCHAR(60) NOT NULL,
  `date` DATETIME NOT NULL,
  `text` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`activityid`),
  INDEX `fk_idx` (`userid` ASC),
  INDEX `pdoduct_idx` (`productid` ASC),
  CONSTRAINT `fk`
    FOREIGN KEY (`userid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`productid`)
    REFERENCES `fb`.`product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`block` (
  `userid` VARCHAR(32) NOT NULL,
  `blockeduserid` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`userid`, `blockeduserid`),
  INDEX `id2_idx` (`blockeduserid` ASC),
  CONSTRAINT `id1`
    FOREIGN KEY (`userid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id2`
    FOREIGN KEY (`blockeduserid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`code` (
  `userid` VARCHAR(32) NOT NULL,
  `otpcode` INT(8) NOT NULL,
  INDEX `codetoid_idx` (`userid` ASC),
  CONSTRAINT `codetoid`
    FOREIGN KEY (`userid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`friends` (
  `userid` VARCHAR(32) NOT NULL,
  `friendid` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`userid`, `friendid`),
  INDEX `frinedstoidmapping_idx` (`userid` ASC, `friendid` ASC),
  INDEX `frid2_idx` (`friendid` ASC),
  CONSTRAINT `frid1`
    FOREIGN KEY (`userid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `frid2`
    FOREIGN KEY (`friendid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`info` (
  `infoid` VARCHAR(60) NOT NULL,
  `receiverid` VARCHAR(32) NOT NULL,
  `senderid` VARCHAR(32) NOT NULL,
  `infotext` TEXT NOT NULL,
  `receiverstatus` TEXT NOT NULL,
  `senderstatus` TEXT NOT NULL,
  `images` TEXT NULL DEFAULT NULL,
  `videos` TEXT NULL DEFAULT NULL,
  `datesent` DATETIME NOT NULL,
  PRIMARY KEY (`infoid`),
  INDEX `sender_idx` (`senderid` ASC),
  INDEX `receiver_idx` (`receiverid` ASC),
  CONSTRAINT `receiver`
    FOREIGN KEY (`receiverid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sender`
    FOREIGN KEY (`senderid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`notification` (
  `notificationid` VARCHAR(60) NOT NULL,
  `receiverid` VARCHAR(32) NOT NULL,
  `senderid` VARCHAR(32) NOT NULL,
  `notificationtype` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`notificationid`),
  UNIQUE INDEX `unique_index` (`receiverid` ASC, `senderid` ASC),
  INDEX `receiverrt_idx` (`receiverid` ASC),
  INDEX `senderee_idx` (`senderid` ASC),
  CONSTRAINT `receiverfuck`
    FOREIGN KEY (`receiverid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `senderfuck`
    FOREIGN KEY (`senderid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fb`.`privacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fb`.`privacy` (
  `userid` VARCHAR(32) NOT NULL,
  `myinfo` TEXT NOT NULL,
  `myfriendlist` TEXT NOT NULL,
  `myphotos` TEXT NOT NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `privacy`
    FOREIGN KEY (`userid`)
    REFERENCES `fb`.`profile` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
